name: clearml_datasets
channels:
  - defaults
dependencies:
  - ca-certificates=2022.4.26
  - certifi=2022.5.18.1
  - libcxx=12.0.0
  - libffi=3.3
  - ncurses=6.3
  - openssl=1.1.1o
  - pip=21.2.4
  - python=3.8.13
  - readline=8.1.2
  - setuptools=61.2.0
  - sqlite=3.38.3
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - attrs==21.4.0
    - charset-normalizer==2.0.12
    - clearml==1.5.0
    - furl==2.1.3
    - future==0.18.2
    - idna==3.3
    - importlib-resources==5.8.0
    - jsonschema==4.6.0
    - numpy==1.22.4
    - orderedmultidict==1.0.1
    - pathlib2==2.3.7.post1
    - pillow==9.1.1
    - psutil==5.9.1
    - pyjwt==2.4.0
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pyyaml==6.0
    - requests==2.28.0
    - six==1.16.0
    - urllib3==1.26.9
    - zipp==3.8.0
